<a href="https://colab.research.google.com/github/aishwaryashetty2805/-https-github.com-rdpeng-ProgrammingAssignment2/blob/master/Day_3_session_2_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000

In [99]:
import pandas as pd
ds = pd.Series([0,2,4,6,8])
print(ds)

0    0
1    2
2    4
3    6
4    8
dtype: int64


2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [111]:
import pandas as pd
ds = pd.Series([1000, 1001, 1002, 1004, 1006,1010,1012,1011])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
ds1 = ds[ds % 5 == 0]
print(ds1.tolist())
print(type(ds1.tolist()))



Pandas Series and type
0    1000
1    1001
2    1002
3    1004
4    1006
5    1010
6    1012
7    1011
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[1000, 1010]
<class 'list'>


3.Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]



In [9]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [13]:
import pandas as pd
ds1 = pd.Series([7, 14, 21, 28, 35,42])
ds2 = pd.Series([11, 22, 33, 44, 55,66])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)
print("Not equal:")
print(ds1 != ds2)


Series1:
0     7
1    14
2    21
3    28
4    35
5    42
dtype: int64
Series2:
0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
Greater than:
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
Less than:
0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool
Not equal:
0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool


5.Write a Pandas program to convert a NumPy array to a Pandas series. 
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]


In [14]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50,60,70,80])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50 60 70 80]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64


6.Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [19]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python','300.12','400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


7.Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [23]:
import pandas as pd
s = pd.Series(['100','200','300','400','500','python','300.12','400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


8.Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
value and condtion :  Subset 1 :numbers divisable by 7  Subset 2 : numbers divisable by 5


In [28]:
import pandas as pd
s = pd.Series([10,20,30,40,50,60,70])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n1 = 7
n2 = 5
new_s1 = s[s % n1 == 0]
new_s2 = s[s % n2 == 0]
print("subset 1-divisible by 7")
print(new_s1)
print("subset 2-divisible by 5")
print(new_s2)


Original Data Series:
0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

Subset of the above Data Series:
subset 1-divisible by 7
6    70
dtype: int64
subset 2-divisible by 5
0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64


9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000



In [113]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,10,11,12,13])
print("Original Data Series:")
print(s)
s1=(s % s == 0)
print("Mean :")
print(s1.mean())
print("Standard deviation :")
print(s1.std())
print("Maximum:")
print(s1.max())
print("Minimum:")
print(s1.min())


Original Data Series:
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
dtype: int64
Mean :
1.0
Standard deviation :
0.0
Maximum:
True
Minimum:
True


10.Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}


In [32]:
import pandas as pd
df = pd.DataFrame({'X':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], 'Y':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],'Z':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]});
print(df)

     X   Y   Z
0    1   1   1
1    2   2   2
2    3   3   3
3    4   4   4
4    5   5   5
5    6   6   6
6    7   7   7
7    8   8   8
8    9   9   9
9   10  10  10
10  11  11  11
11  12  12  12
12  13  13  13
13  14  14  14
14  15  15  15


11.Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [117]:
import pandas as pd
import numpy as np

exam_data  = {'Name': ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O'],
        'Rool No.': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
        'marks': [10, 30, 20, 30, 20, 30, 10, 10, 20, 10,12,14,15,13]}
labels = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o']
print("First 10 rows of the data frame:")
print(df.iloc[:10])


First 10 rows of the data frame:
   roll_no  mark
0      1.0  10.0
1      1.0  11.0
2      1.0  12.0
3      1.0  13.0
4      1.0  14.0
5      1.0  15.0
6      1.0  16.0
7      1.0  17.0
8      1.0  18.0
9      1.0  19.0


12.Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

In [56]:
import numpy as np
import pandas as pd
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('movie_metadata.csv')
seventh_movie = df.iloc[6]
print("Details of the seventh moviee:")
print(seventh_movie)


Saving movie_metadata.csv to movie_metadata (8).csv
Details of the seventh moviee:
color                                                                    Color
director_name                                                        Sam Raimi
num_critic_for_reviews                                                     392
duration                                                                   156
director_facebook_likes                                                      0
actor_3_facebook_likes                                                    4000
actor_2_name                                                      James Franco
actor_1_facebook_likes                                                   24000
gross                                                               3.3653e+08
genres                                                Action|Adventure|Romance
actor_1_name                                                      J.K. Simmons
movie_title                                     

13.
Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields 


In [57]:
import numpy as np
import pandas as pd
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('movie_metadata.csv')
# Create a smaller dataframe
small_df = df[['movie_title', 'actor_1_name', 'num_voted_users','title_year']]
result = small_df.sort_values('title_year')
print("DataFrame based on title_year.")
print(result)


Saving movie_metadata.csv to movie_metadata (9).csv
DataFrame based on title_year.
                                            movie_title  ... title_year
4810  Intolerance: Love's Struggle Throughout the Ages   ...     1916.0
4958                    Over the Hill to the Poorhouse   ...     1920.0
4885                                    The Big Parade   ...     1925.0
2734                                        Metropolis   ...     1927.0
4812                               The Broadway Melody   ...     1929.0
...                                                 ...  ...        ...
4798                                Heroes               ...        NaN
4803                           Home Movies               ...        NaN
4819                            Revolution               ...        NaN
4869                          Happy Valley               ...        NaN
5039                         The Following               ...        NaN

[5043 rows x 4 columns]


14.Write a Pandas program to sort the DataFrame based on country  and language from dataset of  movie_metadata.csv

In [60]:
import numpy as np
import pandas as pd
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('movie_metadata.csv')
result = df.sort_values(by=['country', 'language'], ascending=[True, True])
print("DataFrame based on country and language.")
print(result)


Saving movie_metadata.csv to movie_metadata (12).csv
DataFrame based on country and language.
      color         director_name  ...  movie_facebook_likes  Unnamed: 28
4735  Color         Siddiq Barmak  ...                     0          NaN
4000  Color  Juan José Campanella  ...                 33000          NaN
4415  Color      Fabián Bielinsky  ...                     0          NaN
4450  Color       Lucrecia Martel  ...                    57          NaN
4666  Color         Jorge Gaggero  ...                    83          NaN
...     ...                   ...  ...                   ...          ...
2370  Color                   NaN  ...                     0          NaN
3397  Color                   NaN  ...                 18000          NaN
4021  Color     Daniel Petrie Jr.  ...                   570          NaN
4       NaN           Doug Walker  ...                     0          NaN
279     NaN   Christopher Barnard  ...                     0          NaN

[5043 rows x 29 c

15.Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame #(movie_metadata.csv file).

16.Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of  50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [72]:
import numpy as np
import pandas as pd
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Python_mark.csv')
rd = df.head(50)
print("Mean:")
print(rd['mark'].mean())
print("Standard deviation:")
print(rd['mark'].std())
print("Maximum:")
print(rd['mark'].max())
print("Minimum:")
print(rd['mark'].min())

Saving Python_mark.csv to Python_mark (8).csv
Mean:
34.5
Standard deviation:
14.577379737113251
Maximum:
59.0
Minimum:
10.0


17.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the  array and store them into a variable.

In [80]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 
y= x[1:3,0:4]
print("Second and third rowsof the array:")
print(y)

Original Array:
[[0.98388585 0.18411689 0.22722316 0.58230683]
 [0.33441323 0.51537485 0.82189569 0.6712454 ]
 [0.99095397 0.81195979 0.71224008 0.39770579]
 [0.74370344 0.52873772 0.24006547 0.14808902]]
Second and third rowsof the array:
[[0.33441323 0.51537485 0.82189569 0.6712454 ]
 [0.99095397 0.81195979 0.71224008 0.39770579]]


18.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [96]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum Values:")
print(xmin)
print(" Maximum values")
print(xmax)


Original Array:
[[0.78394676 0.51377542 0.43967811 0.80208472 0.0745965  0.89332407
  0.41865035 0.36982769 0.17427317 0.34642097]
 [0.12826622 0.8768967  0.39523312 0.2632637  0.41184192 0.99912418
  0.60058268 0.39692214 0.88459163 0.99141215]
 [0.13026671 0.14431668 0.22200333 0.15471994 0.83629999 0.61064187
  0.94185447 0.73492813 0.04938605 0.94036563]
 [0.10408166 0.8776547  0.34362596 0.91170398 0.19631577 0.88024746
  0.78328295 0.12364955 0.23432791 0.81596148]
 [0.4728861  0.16467966 0.78549941 0.51063822 0.93310235 0.82931134
  0.273059   0.10847174 0.78934887 0.31722773]
 [0.09993274 0.21495766 0.3697713  0.1379158  0.92208207 0.58757559
  0.4090625  0.2477872  0.87024329 0.31038477]
 [0.68690189 0.18489792 0.19603566 0.24779395 0.96130761 0.19584668
  0.50990859 0.62224561 0.35949152 0.81166278]
 [0.30137561 0.45259488 0.51480451 0.72271224 0.92861661 0.12897341
  0.67413453 0.59773481 0.94572226 0.69382964]
 [0.81139147 0.8637084  0.56817753 0.03262017 0.51530895 0.80333

19.Write a NumPy program to generate 8 random integers between 100 and 300



In [95]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print("8 random integers between 100 and 300")
print(x)

8 random integers between 100 and 300
[235 283 247 101 151 242 136 102]


20.Write a NumPy program to create a random integer nos of size 20 and sort it.

In [93]:
import numpy as np
x = np.random.randint(low=1, high=30, size=20)
print("Original array")
print(x)
x.sort()
print("sorted array")
print(x)

Original array
[26 18  6  4 11  5 18 11 10  4 21  9 11 15 11  6 21  5 14 28]
sorted array
[ 4  4  5  5  6  6  9 10 11 11 11 11 14 15 18 18 21 21 26 28]


In [115]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print("Original")
print(x)
print("After sorting")
x.sort()
print(x)



Original
[19 10 12  6  7  8 13 16  0 15  4  1 14 17  9 11 18  5  3  2]
After sorting
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
